# Copyright 2025 Stas Levchenko
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#     http://www.apache.org/licenses/LICENSE-2.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
data:
  config.yaml: |
    logger:
      level: {{ .Values.config.logger.level | quote }}
    kubernetes:
      include_namespaces: {{ .Values.config.kubernetes.include_namespaces | toJson }}
      exclude_namespaces: {{ .Values.config.kubernetes.exclude_namespaces | toJson }}
    victoria_logs:
      enabled: {{ .Values.config.victorialogs.enabled }}
      endpoint: {{ .Values.config.victorialogs.endpoint | quote }}
      cluster_id: {{ .Values.config.victorialogs.clusterID | quote }}
      account_id: {{ .Values.config.victorialogs.accountID | quote }}
      project_id: {{ .Values.config.victorialogs.projectID | quote }}
      batch_size: {{ .Values.config.victorialogs.batchSize }}
      flush_time: {{ .Values.config.victorialogs.flushTime | quote }}
      timeout: {{ .Values.config.victorialogs.timeout | quote }}
      extra_fields: {{ .Values.config.victorialogs.extraFields | toJson }}
      stream_fields: {{ .Values.config.victorialogs.streamFields | toJson }}
    health:
      port: {{ .Values.config.health.port }}
